services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network
 
volumes:
  db_data:
 
networks:
  app-network:
    driver: bridge